#!/usr/bin/env bash
#
# 发版辅助脚本，由 Justfile 的 release_* recipe 调用（完整流程见根目录 AGENTS.md）。
#
# 之所以有这么一个脚本，而不是把逻辑直接写在 Justfile 里：just 的 shebang recipe 在 Windows 上需要
# cygpath 来翻译解释器路径，而 Git Bash 并不提供它。改成「Justfile 里一行 `bash scripts/release.sh …`」
# 之后，Windows（Git Bash）与 Linux / macOS 都走同一条路径。
#
# Release helper called by the Justfile's release_* recipes (the full flow is in AGENTS.md). It is a
# script rather than raw Justfile lines because just's shebang recipes need `cygpath` to translate the
# interpreter path on Windows, which Git Bash does not ship; a one-line `bash scripts/release.sh …`
# behaves the same on Windows (Git Bash) and on Linux / macOS.
#
# 用法 / Usage：
#   bash scripts/release.sh bump <new-version>   # 项目与文档里的版本号全量替换
#   bash scripts/release.sh dev  <new-version>   # 只把 Cargo 清单切到开发版本
#   bash scripts/release.sh tag  <version>       # 打 tag 并推送，触发 CI 发版
set -euo pipefail

# 替换「文档 / README / CI 注释里的版本号」时跳过的路径。
#
# 比 duckfn 本体的脚本多排除几处，因为**本扩展的版本号会和别的版本号撞字符串**：
#   - Cargo.toml：`quantstats-rs = "<版本>"` 那一行是依赖需求，全局替换会把它一起改掉，所以单独处理；
#   - Cargo.lock：由 `cargo update` 负责；
#   - test/：那里的 `Generated by QuantStats-RS (v. X.Y.Z)` 是 quantstats-rs 报出来的版本号，
#     与本扩展的版本号无关，改了会把测试改坏；
#   - demo/：提交进仓库的行情快照，没有版本号；
#   - AGENTS.md 与本脚本：流程说明，里面的版本号只是示例。
#
# Paths skipped when replacing the version inside docs / READMEs / CI comments. More than duckfn's own
# script excludes, because this extension's version number **collides with other version strings**:
# Cargo.toml's `quantstats-rs = "<version>"` line is a dependency requirement (handled separately),
# Cargo.lock is cargo update's job, `test/` asserts quantstats-rs' own version as the HTML footer prints
# it, `demo/` is a committed market snapshot, and the version numbers in AGENTS.md and in this script are
# examples rather than the project's current release.
DOC_EXCLUDES=(
    ':(exclude)Cargo.toml'
    ':(exclude)Cargo.lock'
    ':(exclude)AGENTS.md'
    ':(exclude)scripts'
    ':(exclude)test'
    ':(exclude)demo'
)

die() {
    echo "error: $*" >&2
    exit 1
}

# 读 [package] 段的 version（不要匹配到别的段，也不要匹配到依赖需求那一行）。
#
# Reads `version` from the `[package]` section only — no other section, and no dependency requirement.
package_version() {
    awk -F'"' '
        /^\[package\]/ { in_section = 1; next }
        /^\[/          { in_section = 0 }
        in_section && /^version *=/ { print $2; exit }
    ' Cargo.toml
}

# 只改 [package] 段的 version 那一行：本文件里还有别的同形字符串（依赖需求那一堆），
# 不能像 duckfn 那样整份文件全局替换。
#
# Rewrites the `version` line of the `[package]` section only: the file holds other strings of the same
# shape (the dependency requirements), so a whole-file replacement like duckfn's would corrupt them.
set_package_version() {
    local new=$1 tmp
    tmp=$(mktemp) || die "无法创建临时文件 / cannot create a temporary file"
    awk -v new="$new" '
        /^\[package\]/           { in_section = 1 }
        /^\[/ && !/^\[package\]/ { in_section = 0 }
        in_section && /^version *=/ { sub(/"[^"]*"/, "\"" new "\"") }
        { print }
    ' Cargo.toml > "$tmp"
    mv "$tmp" Cargo.toml
}

# 最近一次版本 tag（去掉 v 前缀），也就是文档 / CI 注释里示例的版本。
#
# The most recent version tag (without the `v` prefix): the version shown in docs and CI comments.
prev_release_version() {
    local tag
    tag=$(git describe --tags --abbrev=0 --match 'v*' 2>/dev/null || true)
    echo "${tag#v}"
}

# 版本号变了，Cargo.lock 里本扩展自己那一条也要跟上（依赖的版本由 Cargo.toml 的语义化需求管着，
# 这里不动它们）。
#
# After a version change the lock entry for this extension has to follow (dependency versions are
# governed by Cargo.toml's semver requirements and are left alone).
sync_lock() {
    cargo update -p duckfn_quantstats
}

# 把版本号转成能放进 sed 的正则（只需转义点号）。
#
# Turns a version into a sed regex (only the dots need escaping).
sed_escape() {
    printf '%s' "$1" | sed 's/\./\\./g'
}

cmd_bump() {
    local new=$1 dev doc tag escaped files f v now

    dev=$(package_version)
    [ -n "$dev" ] || die "无法从 Cargo.toml 读取 [package] version"

    tag=$(prev_release_version)
    doc=$tag

    if [ "$dev" = "$new" ] && { [ -z "$doc" ] || [ "$doc" = "$new" ]; }; then
        die "版本号已经是 ${new}"
    fi

    # Cargo 清单：项目当前版本 -> 新版本
    if [ "$dev" != "$new" ]; then
        echo "Cargo 版本 ${dev} -> ${new}"
        set_package_version "$new"
    fi

    # 文档 / README / CI 注释：最近一次 tag 的版本 -> 新版本（文件由 git grep 自动找出）。
    # 还没有任何版本 tag 时这一步整体跳过：没有「上一个版本」可替换。
    files=()
    if [ -n "$doc" ] && [ "$doc" != "$new" ]; then
        echo "文档 / CI 版本 ${doc} -> ${new}（取自 ${tag}）"
        mapfile -t files < <(git grep -l -F -- "$doc" -- . "${DOC_EXCLUDES[@]}")
        escaped=$(sed_escape "$doc")
        for f in "${files[@]}"; do
            sed -i "s/${escaped}/${new}/g" "$f"
            echo "  updated $f"
        done
    fi

    sync_lock

    echo
    # 核对 Cargo.toml 只认 [package] 段那一行：对整份文件 grep 版本号会被依赖需求误报。
    now=$(package_version)
    [ "$now" = "$new" ] || die "Cargo.toml 的 [package] version 是 ${now}，期望 ${new}"
    echo "Cargo.toml [package] version = ${now}"

    # 旧版本号残留只在**刚改过的那些文档**里核对，同样是为了避开 test/ 里那个无关的版本号。
    if [ "${#files[@]}" -gt 0 ]; then
        echo "这些文件里残留的旧版本号（应为空 / should be empty）："
        for v in "$dev" "$doc"; do
            [ -n "$v" ] || continue
            [ "$v" = "$new" ] && continue
            grep -n -F -- "$v" "${files[@]}" || true
        done
    fi

    echo
    git --no-pager diff --stat
}

cmd_dev() {
    local new=$1 old

    old=$(package_version)
    if [ -z "$old" ] || [ "$old" = "$new" ]; then
        die "当前版本为 ${old:-未知}，无需切换"
    fi

    set_package_version "$new"
    sync_lock

    git --no-pager diff --stat
    echo "已切换到开发版本 ${new}"
}

cmd_tag() {
    local version=$1 dev

    if ! git diff --quiet || ! git diff --cached --quiet; then
        die "工作区不干净，先提交再打 tag"
    fi

    # tag 必须与 Cargo.toml 的 [package] version 一致：扩展二进制里的版本号是构建时由 cargo 写进去的
    # （`cargo duckdb-ext build` 会打印 "Packing Extension Version"），对不上就会发出一个自称别的
    # 版本的 Release。
    #
    # The tag must match Cargo.toml's `[package] version`: the version inside the built extension is
    # written by cargo at build time (`cargo duckdb-ext build` prints "Packing Extension Version"), so a
    # mismatch would publish a release claiming another version.
    dev=$(package_version)
    if [ "$dev" != "$version" ]; then
        die "Cargo.toml 的版本是 ${dev:-未知}，与要打的 tag v${version} 不一致"
    fi

    git tag "v${version}"
    git push origin main
    git push origin "v${version}"
    echo "已推送 v${version}，用 just release_ci 查看进度"
}

usage() {
    echo "usage: release.sh {bump|dev|tag} <version>" >&2
    exit 2
}

action=${1:-}
[ $# -gt 0 ] && shift

case "$action" in
    bump)
        [ $# -eq 1 ] || usage
        cmd_bump "$1"
        ;;
    dev)
        [ $# -eq 1 ] || usage
        cmd_dev "$1"
        ;;
    tag)
        [ $# -eq 1 ] || usage
        cmd_tag "$1"
        ;;
    *)
        usage
        ;;
esac
