import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is generated from the docs/ folder structure: every markdown file
 * becomes an entry, every folder a category (tune it with a `_category_.json`).
 *
 * To hand-pick the order instead, replace the autogenerated entry below with an
 * explicit list, e.g. `docsSidebar: ['intro', 'quick-start']`.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
