import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * 两个侧边栏，对应顶栏两项（见 docusaurus.config.ts 的 navbar）：
 *
 * - `userGuide` —— 怎么用这个扩展：`intro` 加 `getting-started/`、`guide/` 两个目录。
 * - `development` —— 怎么开发它：`development-guide/` 整棵树。
 *
 * 页面不搬家，URL 因此不变。目录内部的顺序仍由各页的 `sidebar_position` 决定；上面两个分类之所以
 * 手写出来，是因为 `autogenerated` 条目生成的是**目录的内容**、而不是目录本身。
 *
 * Two sidebars, one per navbar entry (see the navbar in docusaurus.config.ts):
 *
 * - `userGuide` — using the extension: `intro` plus the `getting-started/` and `guide/` folders.
 * - `development` — developing it: everything under `development-guide/`.
 *
 * Pages keep the folder they are in, so their URLs stay stable. Inside a folder the order still comes
 * from `sidebar_position`; the two categories below are spelled out because an `autogenerated` entry
 * yields a folder's *contents*, not the folder itself.
 */
const sidebars: SidebarsConfig = {
  userGuide: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      link: {
        type: 'generated-index',
        description: 'Install the extension and produce your first reports — no compiler involved.',
      },
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Guide',
      link: {
        type: 'generated-index',
        description:
          'The two SQL names, every option, the price branch, translation, where the reports go, and the error paths.',
      },
      items: [{type: 'autogenerated', dirName: 'guide'}],
    },
  ],
  development: [{type: 'autogenerated', dirName: 'development-guide'}],
};

export default sidebars;